Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@d-fedorenko-dev 
d-fedorenko-dev
/
natifeforecast
1
00
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
natifeforecast/.github/workflows/T4.yml
@d-fedorenko-dev
d-fedorenko-dev Create T4.yml
Latest commit 642d055 9 minutes ago
 History
 1 contributor
31 lines (26 sloc)  763 Bytes
  
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
